import calendar as calendar
import re as re
import time as time
from datetime import datetime as datetime
from datetime import timezone as timezone
from email.utils import formatdate as formatdate
from email.utils import parsedate as parsedate
from typing import Union

DATE_TIMESPLIT: re.Pattern[str]
TIMESTAMP_14: str
ISO_DT: str
PAD_14_DOWN: str
PAD_14_UP: str
PAD_6_UP: str
PAD_MICRO: str

def iso_date_to_datetime(string: str, tz_aware: bool = False) -> datetime: ...
def http_date_to_datetime(string: str, tz_aware: bool = False) -> datetime: ...
def datetime_to_http_date(the_datetime: datetime) -> str: ...
def datetime_to_iso_date(the_datetime: datetime, use_micros: bool = False) -> str: ...
def datetime_to_timestamp(the_datetime: datetime) -> str: ...
def timestamp_now() -> str: ...
def timestamp20_now() -> str: ...
def iso_date_to_timestamp(string: str) -> str: ...
def timestamp_to_iso_date(string: str) -> str: ...
def http_date_to_timestamp(string: str) -> str: ...
def pad_timestamp(string: str, pad_str: str = PAD_6_UP) -> str: ...
def timestamp_to_datetime(string: str, tz_aware: bool = False) -> datetime: ...
def timestamp_to_sec(string: str) -> int: ...
def sec_to_timestamp(secs: Union[int, float]) -> str: ...
def timestamp_to_http_date(string: str) -> str: ...
