name: CI

on: [push, pull_request]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 3
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10', '3.11']

    steps:
      - name: checkout
        uses: actions/checkout@v4
        
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install urllib3==1.25.11 wheel brotlipy coverage codecov

      - name: Install warcio
        run: python setup.py install

      - name: Run tests
        run: python setup.py test

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
